export { default as Background } from "./background.webp";
// export { default as BackgroundLight } from "./backgroundLight.webp";
// export { default as Background } from "./background.jpg";
export { default as BackgroundLight } from "./backgroundLight.jpg";
export { default as Moon } from "./moon.png";
export { default as Trash1 } from "./trash.png";
export { default as Trash2 } from "./trashh.png";
export { default as Trash3 } from "./trashhh.png";
export { default as Stars } from "./stars.png";
export { default as Light } from "./light.png";
export { default as Cloud } from "./cloud.png";
export { default as Cloud2 } from "./cloud2.png";
export { default as Sun } from "./sun.png";
export { default as MoonDayLight } from "./moon_daylight.png";
